[options]
admin_passwd = mehari123
addons_path = /workspaces/custom-odoo-app/odoo/addons,/workspaces/custom-odoo-app/custom_addons

db_host = localhost
db_port = 5433
db_user = odoo
db_password = odoo

http_port = 8069

